language: node_js

sudo: false

cache: 
  apt: false
  directories: 
    - node_modules

node_js: 
  - '12.16.2'

install:
  - npm install -D
  - cd ./test/smoke/template
  - npm install -D
  - cd ../../

script: 
  - npm test